# Verwende das offizielle PostgreSQL-Image als Basis
FROM postgres:13-alpine

# Setze Umgebungsvariablen für die Datenbank
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB betterbet